name: firebase_app
description: Flutter mobile/desktop app with realtime database

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.4
  dartz: ^0.10.0-nullsafety.1
  firebase_core: ^2.8.0
  firebase_database: ^10.0.16
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  rxdart: ^0.27.7
  google_fonts: ^4.0.3
  firebase_app_check: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  formz: ^0.6.0
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf