name: firebase_app
description: Flutter mobile/desktop app with realtime database

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.6.9
  dartz: ^0.10.0-nullsafety.1
  firebase_core: ^1.0.1
  firebase_database: ^6.1.0
  flutter_bloc: ^7.0.0-nullsafety.4
  freezed_annotation: ^0.14.0
  get_it: ^6.0.0
  injectable: ^1.2.0
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5
  freezed: ^0.14.0
  injectable_generator: ^1.2.0
  json_serializable: ^4.0.2
  lint: ^1.5.3

flutter:
  uses-material-design: true
